package com.juliuscanute.python.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_PythonAssignmentOperator extends EnumerationDescriptorBase {

  public EnumerationDescriptor_PythonAssignmentOperator() {
    super(0x3b1a18ff6fd44977L, 0xba7ea7ddc907c639L, 0x49693ebcac787c48L, "PythonAssignmentOperator", "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217391709256");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_aoAssign_0 = new EnumerationDescriptor.MemberDescriptor("aoAssign", "=", 0x49693ebcac787c49L, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217391709257");
  private final EnumerationDescriptor.MemberDescriptor myMember_aoAdd_0 = new EnumerationDescriptor.MemberDescriptor("aoAdd", "+=", 0x49693ebcac787c4aL, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217391709258");
  private final EnumerationDescriptor.MemberDescriptor myMember_aoSub_0 = new EnumerationDescriptor.MemberDescriptor("aoSub", "-=", 0x49693ebcac787c4dL, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217391709261");
  private final EnumerationDescriptor.MemberDescriptor myMember_aoDiv_0 = new EnumerationDescriptor.MemberDescriptor("aoDiv", "/=", 0x49693ebcac787c51L, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217391709265");
  private final EnumerationDescriptor.MemberDescriptor myMember_aoMul_0 = new EnumerationDescriptor.MemberDescriptor("aoMul", "*=", 0x49693ebcac787c56L, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217391709270");
  private final EnumerationDescriptor.MemberDescriptor myMember_aoRem_0 = new EnumerationDescriptor.MemberDescriptor("aoRem", "%=", 0x49693ebcac787c5cL, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217391709276");
  private final EnumerationDescriptor.MemberDescriptor myMember_aoAnd_0 = new EnumerationDescriptor.MemberDescriptor("aoAnd", "&=", 0x49693ebcac787c63L, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217391709283");
  private final EnumerationDescriptor.MemberDescriptor myMember_aoOr_0 = new EnumerationDescriptor.MemberDescriptor("aoOr", "|=", 0x49693ebcac787c6bL, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217391709291");
  private final EnumerationDescriptor.MemberDescriptor myMember_aoXor_0 = new EnumerationDescriptor.MemberDescriptor("aoXor", "^=", 0x49693ebcac787c74L, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217391709300");
  private final EnumerationDescriptor.MemberDescriptor myMember_aoLS_0 = new EnumerationDescriptor.MemberDescriptor("aoLS", "<<=", 0x49693ebcac787c7eL, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217391709310");
  private final EnumerationDescriptor.MemberDescriptor myMember_aoRS_0 = new EnumerationDescriptor.MemberDescriptor("aoRS", ">>=", 0x49693ebcac787c89L, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217391709321");
  private final EnumerationDescriptor.MemberDescriptor myMember_aoIntDiv_0 = new EnumerationDescriptor.MemberDescriptor("aoIntDiv", "//=", 0x49693ebcac787c95L, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217391709333");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x3b1a18ff6fd44977L, 0xba7ea7ddc907c639L, 0x49693ebcac787c48L, 0x49693ebcac787c49L, 0x49693ebcac787c4aL, 0x49693ebcac787c4dL, 0x49693ebcac787c51L, 0x49693ebcac787c56L, 0x49693ebcac787c5cL, 0x49693ebcac787c63L, 0x49693ebcac787c6bL, 0x49693ebcac787c74L, 0x49693ebcac787c7eL, 0x49693ebcac787c89L, 0x49693ebcac787c95L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_aoAssign_0, myMember_aoAdd_0, myMember_aoSub_0, myMember_aoDiv_0, myMember_aoMul_0, myMember_aoRem_0, myMember_aoAnd_0, myMember_aoOr_0, myMember_aoXor_0, myMember_aoLS_0, myMember_aoRS_0, myMember_aoIntDiv_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_aoAssign_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "aoAssign":
        return myMember_aoAssign_0;
      case "aoAdd":
        return myMember_aoAdd_0;
      case "aoSub":
        return myMember_aoSub_0;
      case "aoDiv":
        return myMember_aoDiv_0;
      case "aoMul":
        return myMember_aoMul_0;
      case "aoRem":
        return myMember_aoRem_0;
      case "aoAnd":
        return myMember_aoAnd_0;
      case "aoOr":
        return myMember_aoOr_0;
      case "aoXor":
        return myMember_aoXor_0;
      case "aoLS":
        return myMember_aoLS_0;
      case "aoRS":
        return myMember_aoRS_0;
      case "aoIntDiv":
        return myMember_aoIntDiv_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
