package com.juliuscanute.python.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class PythonClassStatement_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("class ");
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.className$ZmdT));
    tgs.append(" :");
    tgs.newLine();
    tgs.increaseIndent();
    if ((SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.initFunction$TiZE) != null)) {
      tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.initFunction$TiZE));
      tgs.newLine();
    }
    for (SNode function : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.memberFunctions$ZrBg))) {
      tgs.appendNode(function);
      tgs.newLine();
    }
    tgs.decreaseIndent();
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink className$ZmdT = MetaAdapterFactory.getContainmentLink(0x3b1a18ff6fd44977L, 0xba7ea7ddc907c639L, 0x4e7b579a88a8e92bL, 0x4e7b579a88aa3297L, "className");
    /*package*/ static final SContainmentLink initFunction$TiZE = MetaAdapterFactory.getContainmentLink(0x3b1a18ff6fd44977L, 0xba7ea7ddc907c639L, 0x4e7b579a88a8e92bL, 0x4e7b579a8980366fL, "initFunction");
    /*package*/ static final SContainmentLink memberFunctions$ZrBg = MetaAdapterFactory.getContainmentLink(0x3b1a18ff6fd44977L, 0xba7ea7ddc907c639L, 0x4e7b579a88a8e92bL, 0x4e7b579a88aa3299L, "memberFunctions");
  }
}
