package com.juliuscanute.python.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.AbstractIntentionAspectDescriptor;
import jetbrains.mps.openapi.intentions.IntentionFactory;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.HashMap;
import org.jetbrains.annotations.Nullable;
import java.util.Collection;
import org.jetbrains.annotations.NotNull;
import java.util.Arrays;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class IntentionsDescriptor extends AbstractIntentionAspectDescriptor {
  private static final IntentionFactory[] EMPTY_ARRAY = new IntentionFactory[0];
  private Map<SAbstractConcept, IntentionFactory[]> myCached = new HashMap<SAbstractConcept, IntentionFactory[]>();

  public IntentionsDescriptor() {
  }

  @Nullable
  public Collection<IntentionFactory> getIntentions(@NotNull SAbstractConcept concept) {
    if (myCached.containsKey(concept)) {
      return Arrays.asList(myCached.get(concept));
    }

    IntentionFactory[] intentions = EMPTY_ARRAY;
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        if (true) {
          // concept 
          intentions = new IntentionFactory[1];
          intentions[0] = new PythonCallExpression_toggleArguments_Intention();
        }
        break;
      case 1:
        if (true) {
          // concept 
          intentions = new IntentionFactory[1];
          intentions[0] = new PythonClassStatement__toggleInit_Intention();
        }
        break;
      case 2:
        if (true) {
          // concept 
          intentions = new IntentionFactory[1];
          intentions[0] = new PythonForStatement_toggleElse_Intention();
        }
        break;
      case 3:
        if (true) {
          // concept 
          intentions = new IntentionFactory[1];
          intentions[0] = new PythonIfElseStatement_toggleElse_Intention();
        }
        break;
      case 4:
        if (true) {
          // concept 
          intentions = new IntentionFactory[1];
          intentions[0] = new PythonMemberExpression_toggleIdentifierExpressionProperty_Intention();
        }
        break;
      case 5:
        if (true) {
          // concept 
          intentions = new IntentionFactory[1];
          intentions[0] = new PythonTryExceptStatement_toggleAs_Intention();
        }
        break;
      case 6:
        if (true) {
          // concept 
          intentions = new IntentionFactory[3];
          intentions[0] = new PythonTryStatement_toggleFinally_Intention();
          intentions[1] = new PythonTryStatement_toggleExcept_Intention();
          intentions[2] = new PythonTryStatement_toggleElse_Intention();
        }
        break;
      case 7:
        if (true) {
          // concept 
          intentions = new IntentionFactory[1];
          intentions[0] = new PythonWhileStatement_toggleElse_Intention();
        }
        break;
      default:
    }
    myCached.put(concept, intentions);
    return Arrays.asList(intentions);
  }

  @NotNull
  @Override
  public Collection<IntentionFactory> getAllIntentions() {
    IntentionFactory[] rv = new IntentionFactory[10];
    rv[0] = new PythonWhileStatement_toggleElse_Intention();
    rv[1] = new PythonIfElseStatement_toggleElse_Intention();
    rv[2] = new PythonForStatement_toggleElse_Intention();
    rv[3] = new PythonMemberExpression_toggleIdentifierExpressionProperty_Intention();
    rv[4] = new PythonCallExpression_toggleArguments_Intention();
    rv[5] = new PythonTryStatement_toggleFinally_Intention();
    rv[6] = new PythonTryStatement_toggleExcept_Intention();
    rv[7] = new PythonTryStatement_toggleElse_Intention();
    rv[8] = new PythonTryExceptStatement_toggleAs_Intention();
    rv[9] = new PythonClassStatement__toggleInit_Intention();
    return Arrays.asList(rv);
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x3b1a18ff6fd44977L, 0xba7ea7ddc907c639L, 0x4e7b579a8878efbeL), MetaIdFactory.conceptId(0x3b1a18ff6fd44977L, 0xba7ea7ddc907c639L, 0x4e7b579a88a8e92bL), MetaIdFactory.conceptId(0x3b1a18ff6fd44977L, 0xba7ea7ddc907c639L, 0x4e7b579a889ab886L), MetaIdFactory.conceptId(0x3b1a18ff6fd44977L, 0xba7ea7ddc907c639L, 0x4e7b579a88263da6L), MetaIdFactory.conceptId(0x3b1a18ff6fd44977L, 0xba7ea7ddc907c639L, 0x4e7b579a88ab8976L), MetaIdFactory.conceptId(0x3b1a18ff6fd44977L, 0xba7ea7ddc907c639L, 0x4e7b579a88e103dcL), MetaIdFactory.conceptId(0x3b1a18ff6fd44977L, 0xba7ea7ddc907c639L, 0x4e7b579a88e103dbL), MetaIdFactory.conceptId(0x3b1a18ff6fd44977L, 0xba7ea7ddc907c639L, 0x49693ebcac94e877L)).seal();
}
