package com.juliuscanute.python.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class PythonMemberExpression_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    if ((SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.object$hpLa) != null)) {
      tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.object$hpLa));
    }
    if ((SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.identifierProperty$hqHe) != null)) {
      tgs.append(".");
      tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.identifierProperty$hqHe));
    }
    if ((SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.expressionProperty$hwlA) != null)) {
      tgs.append("[");
      tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.expressionProperty$hwlA));
      tgs.append("]");
    }
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink object$hpLa = MetaAdapterFactory.getContainmentLink(0x3b1a18ff6fd44977L, 0xba7ea7ddc907c639L, 0x4e7b579a88ab8976L, 0x4e7b579a88ab8977L, "object");
    /*package*/ static final SContainmentLink identifierProperty$hqHe = MetaAdapterFactory.getContainmentLink(0x3b1a18ff6fd44977L, 0xba7ea7ddc907c639L, 0x4e7b579a88ab8976L, 0x4e7b579a88ab897bL, "identifierProperty");
    /*package*/ static final SContainmentLink expressionProperty$hwlA = MetaAdapterFactory.getContainmentLink(0x3b1a18ff6fd44977L, 0xba7ea7ddc907c639L, 0x4e7b579a88ab8976L, 0x4e7b579a88ab897eL, "expressionProperty");
  }
}
