package com.juliuscanute.python.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class PythonStringLiteral_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    if (isNotEmptyString(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.singleQuotedValue$VDXc))) {
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.singleQuotedValue$VDXc));
    }
    if (isNotEmptyString(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.doubleQuotedValue$VDva))) {
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.doubleQuotedValue$VDva));
    }
  }
  private static boolean isNotEmptyString(String str) {
    return str != null && str.length() > 0;
  }

  private static final class PROPS {
    /*package*/ static final SProperty singleQuotedValue$VDXc = MetaAdapterFactory.getProperty(0x3b1a18ff6fd44977L, 0xba7ea7ddc907c639L, 0x49693ebcac6e840aL, 0x49693ebcac6e840dL, "singleQuotedValue");
    /*package*/ static final SProperty doubleQuotedValue$VDva = MetaAdapterFactory.getProperty(0x3b1a18ff6fd44977L, 0xba7ea7ddc907c639L, 0x49693ebcac6e840aL, 0x49693ebcac6e840bL, "doubleQuotedValue");
  }
}
