package com.juliuscanute.python.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenAspectBase;
import com.juliuscanute.python.structure.LanguageConceptSwitch;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.text.rt.TextGenDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class TextGenAspectDescriptor extends TextGenAspectBase {
  private final LanguageConceptSwitch myIndex = new LanguageConceptSwitch();

  public TextGenAspectDescriptor() {
  }

  @Nullable
  @Override
  public TextGenDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    switch (myIndex.index(concept)) {
      case LanguageConceptSwitch.PythonBooleanLiteral:
        return new PythonBooleanLiteral_TextGen();
      case LanguageConceptSwitch.PythonNoneLiteral:
        return new PythonNoneLiteral_TextGen();
      case LanguageConceptSwitch.PythonNumericLiteral:
        return new PythonNumericLiteral_TextGen();
      case LanguageConceptSwitch.PythonStringLiteral:
        return new PythonStringLiteral_TextGen();
    }
    return null;
  }

}
