# action.yml
name: 'Build MPS Plugin'
description: 'Builds MPS Plugin from build.xml using Ant'
outputs:
  build-log: # id of output
    description: 'Build completed successfully'
runs:
  using: 'docker'
  image: 'Dockerfile'