package com.juliuscanute.python.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_PythonBinaryOperator extends EnumerationDescriptorBase {

  public EnumerationDescriptor_PythonBinaryOperator() {
    super(0x3b1a18ff6fd44977L, 0xba7ea7ddc907c639L, 0x49693ebcac683be2L, "PythonBinaryOperator", "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217390644194");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_bnEq_0 = new EnumerationDescriptor.MemberDescriptor("bnEq", "==", 0x49693ebcac683be3L, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217390644195");
  private final EnumerationDescriptor.MemberDescriptor myMember_bnInEq_0 = new EnumerationDescriptor.MemberDescriptor("bnInEq", "!=", 0x49693ebcac683be8L, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217390644200");
  private final EnumerationDescriptor.MemberDescriptor myMember_bnLt_0 = new EnumerationDescriptor.MemberDescriptor("bnLt", "<", 0x49693ebcac683bebL, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217390644203");
  private final EnumerationDescriptor.MemberDescriptor myMember_bnLtEq_0 = new EnumerationDescriptor.MemberDescriptor("bnLtEq", "<=", 0x49693ebcac683befL, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217390644207");
  private final EnumerationDescriptor.MemberDescriptor myMember_bnGt_0 = new EnumerationDescriptor.MemberDescriptor("bnGt", ">", 0x49693ebcac683bf4L, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217390644212");
  private final EnumerationDescriptor.MemberDescriptor myMember_bnGtEq_0 = new EnumerationDescriptor.MemberDescriptor("bnGtEq", ">=", 0x49693ebcac683bfaL, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217390644218");
  private final EnumerationDescriptor.MemberDescriptor myMember_bnLs_0 = new EnumerationDescriptor.MemberDescriptor("bnLs", "<<", 0x49693ebcac683c01L, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217390644225");
  private final EnumerationDescriptor.MemberDescriptor myMember_bnRs_0 = new EnumerationDescriptor.MemberDescriptor("bnRs", ">>", 0x49693ebcac683c09L, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217390644233");
  private final EnumerationDescriptor.MemberDescriptor myMember_bnPlus_0 = new EnumerationDescriptor.MemberDescriptor("bnPlus", "+", 0x49693ebcac683c12L, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217390644242");
  private final EnumerationDescriptor.MemberDescriptor myMember_bnMinus_0 = new EnumerationDescriptor.MemberDescriptor("bnMinus", "-", 0x49693ebcac683c1cL, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217390644252");
  private final EnumerationDescriptor.MemberDescriptor myMember_bnMul_0 = new EnumerationDescriptor.MemberDescriptor("bnMul", "*", 0x49693ebcac683c27L, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217390644263");
  private final EnumerationDescriptor.MemberDescriptor myMember_bnDiv_0 = new EnumerationDescriptor.MemberDescriptor("bnDiv", "/", 0x49693ebcac683c33L, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217390644275");
  private final EnumerationDescriptor.MemberDescriptor myMember_bnIntDiv_0 = new EnumerationDescriptor.MemberDescriptor("bnIntDiv", "//", 0x49693ebcac683ceeL, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217390644462");
  private final EnumerationDescriptor.MemberDescriptor myMember_bnMod_0 = new EnumerationDescriptor.MemberDescriptor("bnMod", "%", 0x49693ebcac683c40L, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217390644288");
  private final EnumerationDescriptor.MemberDescriptor myMember_bnOr_0 = new EnumerationDescriptor.MemberDescriptor("bnOr", "|", 0x49693ebcac683c4eL, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217390644302");
  private final EnumerationDescriptor.MemberDescriptor myMember_bnXor_0 = new EnumerationDescriptor.MemberDescriptor("bnXor", "^", 0x49693ebcac683c5dL, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217390644317");
  private final EnumerationDescriptor.MemberDescriptor myMember_bnAnd_0 = new EnumerationDescriptor.MemberDescriptor("bnAnd", "&", 0x49693ebcac683c6dL, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217390644333");
  private final EnumerationDescriptor.MemberDescriptor myMember_bnIn_0 = new EnumerationDescriptor.MemberDescriptor("bnIn", "in", 0x49693ebcac683ca0L, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217390644384");
  private final EnumerationDescriptor.MemberDescriptor myMember_bnNotIn_0 = new EnumerationDescriptor.MemberDescriptor("bnNotIn", "not in", 0x49693ebcac683cb2L, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217390644402");
  private final EnumerationDescriptor.MemberDescriptor myMember_bnIs_0 = new EnumerationDescriptor.MemberDescriptor("bnIs", "is", 0x49693ebcac683cc5L, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217390644421");
  private final EnumerationDescriptor.MemberDescriptor myMember_bnIsNot_0 = new EnumerationDescriptor.MemberDescriptor("bnIsNot", "is not", 0x49693ebcac683cd9L, "r:00f94cb7-1749-461e-9045-70eb5d47fa62(com.juliuscanute.python.structure)/5289828217390644441");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x3b1a18ff6fd44977L, 0xba7ea7ddc907c639L, 0x49693ebcac683be2L, 0x49693ebcac683be3L, 0x49693ebcac683be8L, 0x49693ebcac683bebL, 0x49693ebcac683befL, 0x49693ebcac683bf4L, 0x49693ebcac683bfaL, 0x49693ebcac683c01L, 0x49693ebcac683c09L, 0x49693ebcac683c12L, 0x49693ebcac683c1cL, 0x49693ebcac683c27L, 0x49693ebcac683c33L, 0x49693ebcac683ceeL, 0x49693ebcac683c40L, 0x49693ebcac683c4eL, 0x49693ebcac683c5dL, 0x49693ebcac683c6dL, 0x49693ebcac683ca0L, 0x49693ebcac683cb2L, 0x49693ebcac683cc5L, 0x49693ebcac683cd9L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_bnEq_0, myMember_bnInEq_0, myMember_bnLt_0, myMember_bnLtEq_0, myMember_bnGt_0, myMember_bnGtEq_0, myMember_bnLs_0, myMember_bnRs_0, myMember_bnPlus_0, myMember_bnMinus_0, myMember_bnMul_0, myMember_bnDiv_0, myMember_bnIntDiv_0, myMember_bnMod_0, myMember_bnOr_0, myMember_bnXor_0, myMember_bnAnd_0, myMember_bnIn_0, myMember_bnNotIn_0, myMember_bnIs_0, myMember_bnIsNot_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_bnEq_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "bnEq":
        return myMember_bnEq_0;
      case "bnInEq":
        return myMember_bnInEq_0;
      case "bnLt":
        return myMember_bnLt_0;
      case "bnLtEq":
        return myMember_bnLtEq_0;
      case "bnGt":
        return myMember_bnGt_0;
      case "bnGtEq":
        return myMember_bnGtEq_0;
      case "bnLs":
        return myMember_bnLs_0;
      case "bnRs":
        return myMember_bnRs_0;
      case "bnPlus":
        return myMember_bnPlus_0;
      case "bnMinus":
        return myMember_bnMinus_0;
      case "bnMul":
        return myMember_bnMul_0;
      case "bnDiv":
        return myMember_bnDiv_0;
      case "bnIntDiv":
        return myMember_bnIntDiv_0;
      case "bnMod":
        return myMember_bnMod_0;
      case "bnOr":
        return myMember_bnOr_0;
      case "bnXor":
        return myMember_bnXor_0;
      case "bnAnd":
        return myMember_bnAnd_0;
      case "bnIn":
        return myMember_bnIn_0;
      case "bnNotIn":
        return myMember_bnNotIn_0;
      case "bnIs":
        return myMember_bnIs_0;
      case "bnIsNot":
        return myMember_bnIsNot_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
