package com.juliuscanute.python.structure;

/*Generated by MPS */

import java.util.Set;
import jetbrains.mps.internal.collections.runtime.SetSequence;
import java.util.HashSet;

public class PythonIdentifierConstraintsUtil {
  private static Set<String> pythonScriptReservedWords = SetSequence.fromSetAndArray(new HashSet<String>(), new String[]{"break", "case", "catch", "continue", "debugger", "default", "delete", "do", "else", "finally", "for", "function", "if", "in", "instanceof", "new", "return", "switch", "this", "throw", "try", "typeof", "var", "void", "while", "with", "null", "true", "false"});
  private PythonIdentifierConstraintsUtil() {
  }
  public static boolean isPythonScriptReservedWord(String s) {
    return SetSequence.fromSet(pythonScriptReservedWords).contains(s);
  }

}
