on: [push]

jobs:
  mps_build_job:
    runs-on: ubuntu-latest
    name: MPS Plugin
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use MPS Docker Container
      id: mps-build
      uses: ./actions/mps-docker-action
      with:
        mount-root: '--volume=./common/:/github/workspace'
    # Use the output from the `hello` step
    - name: Print output log
      run: echo "${{ steps.mps-build.outputs.build-log }}"
    - uses: actions/upload-artifact@v2
      with:
        name: mps-python
        path: ./common/build/artifacts/Python/Python.zip